Updating publish

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -8,11 +8,9 @@ permissions:
   id-token: "write"
 
 jobs:
-  publish:
+  test:
     runs-on: [self-hosted, Linux, external-k8s]
     environment: "non_production"
-    env:
-      INPUT_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
 
     strategy:
       matrix:
@@ -36,7 +34,49 @@ jobs:
 
       - name: Configure NPM
         env:
-          ARTIFACTORY_TOKEN: ${{secrets.ARTIFACTORY_TOKEN}}
+          ARTIFACTORY_TOKEN: ${{secrets.ARTIFACTORY_AUTH}}
+        run: |
+          npm config set registry https://registry.npmjs.org/
+          npm config set @monsantoit:registry https://artifactory.bayer.com/artifactory/api/npm/npm-platforms-engineering/
+          npm config set @bayerit:registry https://artifactory.bayer.com/artifactory/api/npm/npm-platforms-engineering/
+          npm config set @element:registry https://artifactory.bayer.com/artifactory/api/npm/npm-platforms-engineering/
+          npm config set //artifactory.bayer.com/artifactory/api/npm/npm-platforms-engineering/:_password $ARTIFACTORY_TOKEN
+          npm config set //artifactory.bayer.com/artifactory/api/npm/npm-platforms-engineering/:username discoverylab-formgenerator
+          npm config set //artifactory.bayer.com/artifactory/api/npm/npm-platforms-engineering/:email cathy.richards@bayer.com
+
+      - name: Install Dependencies
+        run: npm ci
+
+  publish:
+    runs-on: [self-hosted, Linux, external-k8s]
+    environment: "non_production"
+    needs: test
+    env:
+      INPUT_TOKEN: ${{ secrets.ARTIFACTORY_AUTH }}
+
+    strategy:
+      matrix:
+        node-version: [18.x]
+
+    steps:
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v3
+        with:
+          node-version: ${{ matrix.node-version }}
+
+      # Taken from https://github.com/AutoModality/action-clean (felt too small to include as an action)
+      - name: Clean Workspace Files
+        run: |
+          set -e # fail on error
+          shopt -s dotglob
+          sudo rm -rf *
+
+      - name: Checking out from GitHub
+        uses: actions/checkout@v3
+
+      - name: Configure NPM
+        env:
+          ARTIFACTORY_TOKEN: ${{secrets.ARTIFACTORY_AUTH}}
         run: |
           npm config set registry https://registry.npmjs.org/
           npm config set @monsantoit:registry https://artifactory.bayer.com/artifactory/api/npm/npm-platforms-engineering/
@@ -76,7 +116,7 @@ jobs:
         uses: JS-DevTools/npm-publish@v1
         with:
           registry: https://artifactory.bayer.com/artifactory/api/npm/npm-platforms-engineering/
-          token: ${{secrets.ARTIFACTORY_TOKEN}}
+          token: ${{secrets.ARTIFACTORY_AUTH}}
 
       - name: Git Tag
         run: |
